PROJETO POWER BI DA PREFEITURA DE RECIFE

In [389]:
import numpy as np
import pandas as pd
from google.colab import files

In [390]:
dataSet = pd.read_csv('/content/BaseGeralPrefeitura.csv', sep = ";", encoding="ISO-8859-1")

# **READ**

In [391]:
dataSet.head(1-2)

,Nome da Origem,ano,codigo_escola,escola,endereco_bairro,endereco_logradouro,endereco_numero,rpa,ano_ensino,modalidade_ensino_codigo,serie_codigo,modalidade_ensino,serie,turma,turno,matricula,sexo,idade,situacao_codigo,situacao_nome
0,situacaofinal2019.csv,2019.0,146.0,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,S/N,6.0,GRUPO V,0.0,5.0,EDUCACAO INFANTIL,GRUPO V,A,MANHÃ,17690811.0,2.0,6.0,AP,APROVADO
1,situacaofinal2019.csv,2019.0,146.0,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,S/N,6.0,GRUPO V,0.0,5.0,EDUCACAO INFANTIL,GRUPO V,A,MANHÃ,15028380.0,2.0,6.0,AP,APROVADO
2,situacaofinal2019.csv,2019.0,146.0,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,S/N,6.0,GRUPO V,0.0,5.0,EDUCACAO INFANTIL,GRUPO V,A,MANHÃ,18098843.0,2.0,6.0,AP,APROVADO
3,situacaofinal2019.csv,2019.0,146.0,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,S/N,6.0,GRUPO V,0.0,5.0,EDUCACAO INFANTIL,GRUPO V,A,MANHÃ,17049660.0,2.0,5.0,AP,APROVADO
4,situacaofinal2019.csv,2019.0,146.0,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,S/N,6.0,GRUPO V,0.0,5.0,EDUCACAO INFANTIL,GRUPO V,A,MANHÃ,18691986.0,1.0,6.0,AP,APROVADO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145527,situacaofinal2020.csv,2020.0,40.0,MAGALHAES BASTOS,VARZEA,FRANCISCO LACERDA,S/N,4.0,4º ANO,1.0,3.0,ENSINO FUNDAMENTAL,4º ANO,B,MANHÃ,13017187.0,2.0,12.0,AP,APROVADO
145528,situacaofinal2020.csv,2020.0,40.0,MAGALHAES BASTOS,VARZEA,FRANCISCO LACERDA,S/N,4.0,4º ANO,1.0,3.0,ENSINO FUNDAMENTAL,4º ANO,B,MANHÃ,15614522.0,2.0,9.0,AP,APROVADO
145529,situacaofinal2020.csv,2020.0,40.0,MAGALHAES BASTOS,VARZEA,FRANCISCO LACERDA,S/N,4.0,4º ANO,1.0,3.0,ENSINO FUNDAMENTAL,4º ANO,B,MANHÃ,11515376.0,2.0,15.0,AP,APROVADO
145530,situacaofinal2020.csv,2020.0,40.0,MAGALHAES BASTOS,VARZEA,FRANCISCO LACERDA,S/N,4.0,4º ANO,1.0,3.0,ENSINO FUNDAMENTAL,4º ANO,B,MANHÃ,17654351.0,2.0,10.0,AP,APROVADO
145531,situacaofinal2020.csv,2020.0,40.0,MAGALHAES BASTOS,VARZEA,FRANCISCO LACERDA,S/N,4.0,4º ANO,1.0,3.0,ENSINO FUNDAMENTAL,4º ANO,B,MANHÃ,14018390.0,1.0,10.0,TR,TR DUR ANO FORA REDE

In [392]:
dataSet.isnull().sum()

Nome da Origem                 0
ano                            1
codigo_escola                  1
escola                         1
endereco_bairro                1
endereco_logradouro          534
endereco_numero                1
rpa                            1
ano_ensino                     1
modalidade_ensino_codigo       1
serie_codigo                3473
modalidade_ensino              1
serie                         19
turma                          1
turno                          1
matricula                      1
sexo                           1
idade                          1
situacao_codigo                1
situacao_nome                  1
dtype: int64

# ***DROP***

In [393]:
dataSet = dataSet.drop(columns=["serie_codigo"])
dataSet = dataSet.drop(columns=["situacao_codigo"])
# dataSet = dataSet.drop(columns=["Nome da Origem"])

In [394]:
# print(dataSet[dataSet.isna().any(axis=1)])

In [395]:
# dataSet = dataSet.dropna()

# **ALTER**

### **Alterando os tipos**

In [396]:
dataSet.dtypes

Nome da Origem               object
ano                         float64
codigo_escola               float64
escola                       object
endereco_bairro              object
endereco_logradouro          object
endereco_numero              object
rpa                         float64
ano_ensino                   object
modalidade_ensino_codigo    float64
modalidade_ensino            object
serie                        object
turma                        object
turno                        object
matricula                   float64
sexo                        float64
idade                       float64
situacao_nome                object
dtype: object

In [397]:
dataSet["ano"] = dataSet["ano"].astype(str)
dataSet["codigo_escola"] = pd.to_numeric(dataSet["codigo_escola"])
dataSet["escola"] = dataSet["escola"].astype(str)
dataSet["endereco_bairro"] = dataSet["endereco_bairro"].astype(str)
dataSet["endereco_logradouro"] = dataSet["endereco_logradouro"].astype(str)
dataSet["endereco_numero"] = dataSet["endereco_numero"].astype(str)
dataSet["rpa"] = dataSet["rpa"].astype(str)
dataSet["ano_ensino"] = dataSet["ano_ensino"].astype(str)
dataSet["modalidade_ensino_codigo"] = pd.to_numeric(dataSet["modalidade_ensino_codigo"])
dataSet["modalidade_ensino"] = dataSet["modalidade_ensino"].astype(str)
dataSet["turma"] = dataSet["turma"].astype(str)
dataSet["turno"] = dataSet["turno"].astype(str)
dataSet["matricula"] = pd.to_numeric(dataSet["matricula"])
dataSet["sexo"] = dataSet["sexo"].astype(str)
dataSet["situacao_nome"] = dataSet["situacao_nome"].astype(str)

### **Alterando valores**

alterando valor de sexo

In [398]:
dataSet['sexo'].unique()

array(['2.0', '1.0', 'nan'], dtype=object)

In [399]:
dataSet['sexo'] = dataSet['sexo'].replace({
    "1": "Masculino",
    "2": "Feminino",
    "3": "Feminino"
})

Alterando valor de modalidade_ensino

In [400]:
dataSet['modalidade_ensino'].unique()

array(['EDUCACAO INFANTIL', 'ENSINO FUNDAMENTAL',
       'EDUCACAO  JOVENS E ADULTOS', 'CORREÇÃO DE FLUXO', 'PROJOVEM',
       'nan'], dtype=object)

In [401]:
dataSet['modalidade_ensino'] = dataSet['modalidade_ensino'].str.strip().replace({
    "EDUCACAO JOVENS E ADULTOS": "EDUCACAO JOVENS E ADULTOS",
    "EDUCACAO  JOVENS E ADULTOS": "EDUCACAO JOVENS E ADULTOS",
    "PROJOVEM": "EDUCACAO JOVENS E ADULTOS"
})

Alterando endereco_numero

In [402]:
dataSet['endereco_numero'].unique()

array(['S/N', '653', '685', '180', '338', '369', '356', '1265', '255',
       '250', '300', 'SN', '53', '813', '198', '134', '1470', '37', '120',
       '1340', '290', '55', '82', '303', '80', '100', '453', '28', '84',
       '1595', '189', '131', '112', '111', '310', '450', '375', '1441',
       '5449', '48', '284', '10', '415', '633', '395', '19', '244', '479',
       '68', '1555', '215', '500', '25', '287', '83', '165', '568', '105',
       '49', '30', '7696', '127', '117', '35', '115', '175', '240', '427',
       '600', '320', '1138', '591', '91', '110', '925', '360', '222',
       '69', '211', '227', '655', '36', '85', '301', '304', '12', '13',
       '1406', '135', '437', '686', '440', '1864', '419', '498', '09',
       '273', '283', '1107', '51', '3895', '107', '350', '52', '125',
       '1316', '468', '700', '204', '42', '54', '508', '269', '176',
       '147', '157', '60', '1307', '318', '677', '182', '1030', '07',
       '900', '2173', '669', '109', '720', '56', '169', '24', '417',
       '1045', '511', '236', '141', '1040', '172', '21', '145', '27',
       '200', '216', '118', '43', '279', '594', '461', '377', '950',
       '545', '7636', '1848', '386', '168', '170', '399', '41', '541',
       '31', '660', '5785', '368', '225', '4900', '104', '2191', '160',
       '122', '2526', '140', '33', '470', '5400', '70', '570', '16',
       '364', '164', '50', '1800', '20', '248', '390', '123', '86', '218',
       '126A', '14', '1530', '65', '116', '73', '1536', '1120', 'nan'],
      dtype=object)

In [403]:
dataSet.loc[dataSet['endereco_numero'] == "S/N", 'endereco_numero'] = "SN"

Alterando RPA (Região Político Administrativa)

In [404]:
dataSet['rpa'].unique()

array(['6.0', '4.0', '2.0', '1.0', '5.0', '3.0', 'nan'], dtype=object)

In [405]:
dataSet['rpa'] = dataSet['rpa'].replace({
    "1": "CENTRO",
    "2": "NORTE",
    "3": "NOROESTE",
    "4": "OESTE",
    "5": "SUDOESTE",
    "6": "SUL"
})

Alterando situação_nome

In [406]:
dataSet['situacao_nome'].unique()

array(['APROVADO', 'RETIDO POR FALTA', 'TR DUR ANO FORA REDE',
       'DESISTENTE', 'RETIDO', 'TR DUR ANO P/REDE', 'REPROV P/  FALTA',
       'DESIST/DEIXOU FREQUE', 'REMANEJADO', 'RECLASSIFICADO',
       'RENV S/SIT FINAL DEF', 'FALECIDO', 'RT FALTA TR P/REDE',
       'RETIDO POR IDADE', 'nan'], dtype=object)

In [407]:
dataSet['situacao_nome'].value_counts()

situacao_nome
APROVADO                126910
TR DUR ANO FORA REDE      5153
RETIDO                    3828
RETIDO POR FALTA          2694
TR DUR ANO P/REDE         1604
DESISTENTE                1588
RENV S/SIT FINAL DEF      1481
DESIST/DEIXOU FREQUE      1047
REPROV P/  FALTA           832
REMANEJADO                 327
FALECIDO                    49
RECLASSIFICADO              11
RT FALTA TR P/REDE           4
RETIDO POR IDADE             4
nan                          1
Name: count, dtype: int64

In [408]:
dataSet['situacao_nome'] = dataSet['situacao_nome'].replace({
    "RETIDO": "REPROVADO",
    "RETIDO POR FALTA": "REPROVADO POR FALTA",
    "REPROV P/  FALTA": "REPROVADO POR FALTA",
    "TR DUR ANO S/INFO": "TRANSFERÊNCIA",
    "RETIDO POR IDADE": "REPROVADO",
    "RT FALTA TR P/REDE": "TR DUR ANO P/REDE",
    "RETIDO E TR P/ REDE": "TR DUR ANO P/REDE",
    "Transferência": "TRANSFERÊNCIA",
    "DESIST/DEIXOU FREQUE": "DESISTENTE",
    "DESIST REN C/ TRANSF": "TRANSFERÊNCIA",
    "RENV S/SIT FINAL DEF": "RENV NÃO DEFINIDA",
    "FREQÜENTE": "APROVADO"

})

# **CREATE**

In [409]:
def faixa_etaria(idade):
    if idade <= 12:
        return 'Criança'
    elif 13 <= idade <= 18:
        return 'Adolescente'
    elif 19 <= idade <= 65:
        return 'Adulto'
    else:
        return 'Idoso'

dataSet['faixa_etaria'] = dataSet['idade'].apply(faixa_etaria)

# **SAVE**

In [410]:
dataSet.to_csv('/content/BaseGeralPrefeitura_tratada.csv', index=False, sep=";")

In [411]:
files.download('/content/BaseGeralPrefeitura_tratada.csv')