PROJETO POWER BI DA PREFEITURA DE RECIFE

In [ ]:
import numpy as np
import pandas as pd
from google.colab import files

In [ ]:
dataSet = pd.read_csv('/content/situacaofinal2018.csv', sep=";")

# **READ**

In [ ]:
dataSet.head(1-2)

,ano,codigo_escola,escola,endereco_bairro,endereco_logradouro,endereco_numero,rpa,ano_ensino,modalidade_ensino_codigo,serie_codigo,modalidade_ensino,turma,turno,matricula,sexo,idade,situacao_codigo,situacao_nome
0,2018,146,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,SN,SUL,GRUPO V,0,5.0,EDUCACAO INFANTIL,A,MANHÃ,17696089,Feminino,6,AP,APROVADO
1,2018,146,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,SN,SUL,GRUPO V,0,5.0,EDUCACAO INFANTIL,A,MANHÃ,16767969,Masculino,6,AP,APROVADO
2,2018,146,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,SN,SUL,GRUPO V,0,5.0,EDUCACAO INFANTIL,A,MANHÃ,17638470,Feminino,6,AP,APROVADO
3,2018,146,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,SN,SUL,GRUPO V,0,5.0,EDUCACAO INFANTIL,A,MANHÃ,17073731,Masculino,6,AP,APROVADO
4,2018,146,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,SN,SUL,GRUPO V,0,5.0,EDUCACAO INFANTIL,A,MANHÃ,17711606,Feminino,6,AP,APROVADO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96652,2018,133,27 DE NOVEMBRO,COHAB,DOZE DE JUNHO,1120,SUL,5º ANO,1,4.0,ENSINO FUNDAMENTAL,B,TARDE,12052191,Feminino,12,AP,APROVADO
96653,2018,133,27 DE NOVEMBRO,COHAB,DOZE DE JUNHO,1120,SUL,5º ANO,1,4.0,ENSINO FUNDAMENTAL,B,TARDE,17713455,Masculino,12,AP,APROVADO
96654,2018,133,27 DE NOVEMBRO,COHAB,DOZE DE JUNHO,1120,SUL,5º ANO,1,4.0,ENSINO FUNDAMENTAL,B,TARDE,7066520,Feminino,14,TA,TR DUR ANO P/REDE
96655,2018,133,27 DE NOVEMBRO,COHAB,DOZE DE JUNHO,1120,SUL,5º ANO,1,4.0,ENSINO FUNDAMENTAL,B,TARDE,16087313,Masculino,11,AP,APROVADO
96656,2018,133,27 DE NOVEMBRO,COHAB,DOZE DE JUNHO,1120,SUL,5º ANO,1,4.0,ENSINO FUNDAMENTAL,B,TARDE,12094870,Masculino,11,AP,APROVADO

In [ ]:
dataSet.isnull().sum()

ano                            0
codigo_escola                  0
escola                         0
endereco_bairro                0
endereco_logradouro            0
endereco_numero                0
rpa                            0
ano_ensino                     0
modalidade_ensino_codigo       0
serie_codigo                2467
modalidade_ensino              0
turma                          0
turno                          0
matricula                      0
sexo                           0
idade                          0
situacao_codigo                0
situacao_nome                  0
faixa_etaria                   0
progressao                     0
dtype: int64

# ***DROP***

In [ ]:
dataSet = dataSet.drop(columns=["serie"])

# **ALTER**

### **Alterando os tipos**

In [ ]:
dataSet.dtypes

ano                          int64
codigo_escola                int64
escola                      object
endereco_bairro             object
endereco_logradouro         object
endereco_numero             object
rpa                          int64
ano_ensino                  object
modalidade_ensino_codigo     int64
serie_codigo                object
modalidade_ensino           object
turma                       object
turno                       object
matricula                    int64
sexo                         int64
idade                        int64
situacao_codigo             object
situacao_nome               object
dtype: object

In [ ]:
dataSet["ano"] = dataSet["ano"].astype(str)
dataSet["codigo_escola"] = pd.to_numeric(dataSet["codigo_escola"])
dataSet["escola"] = dataSet["escola"].astype(str)
dataSet["endereco_bairro"] = dataSet["endereco_bairro"].astype(str)
dataSet["endereco_logradouro"] = dataSet["endereco_logradouro"].astype(str)
dataSet["endereco_numero"] = dataSet["endereco_numero"].astype(str)
dataSet["rpa"] = dataSet["rpa"].astype(str)
dataSet["ano_ensino"] = dataSet["ano_ensino"].astype(str)
dataSet["modalidade_ensino_codigo"] = pd.to_numeric(dataSet["modalidade_ensino_codigo"])
dataSet["serie_codigo"] = pd.to_numeric(dataSet["serie_codigo"], errors='coerce')
dataSet["modalidade_ensino"] = dataSet["modalidade_ensino"].astype(str)
dataSet["turma"] = dataSet["turma"].astype(str)
dataSet["turno"] = dataSet["turno"].astype(str)
dataSet["matricula"] = pd.to_numeric(dataSet["matricula"])
dataSet["sexo"] = dataSet["sexo"].astype(str)
dataSet["situacao_codigo"] = dataSet["situacao_codigo"].astype(str)
dataSet["situacao_nome"] = dataSet["situacao_nome"].astype(str)

### **Alterando valores**

alterando valor de sexo

In [ ]:
dataSet['sexo'].unique()

array(['2', '1'], dtype=object)

In [ ]:
dataSet.loc[dataSet['sexo'] == "3", 'sexo'] = "2"
dataSet.loc[dataSet['sexo'] == "1", 'sexo'] = "Masculino"
dataSet.loc[dataSet['sexo'] == "2", 'sexo'] = "Feminino"

Alterando valor de modalidade_ensino

In [ ]:
dataSet['modalidade_ensino'].unique()

array(['EDUCACAO INFANTIL', 'ENSINO FUNDAMENTAL',
       'EDUCACAO  JOVENS E ADULTOS', 'CORREÇÃO DE FLUXO'], dtype=object)

In [ ]:
dataSet['modalidade_ensino'] = dataSet['modalidade_ensino'].str.strip().replace({
    "EDUCACAO JOVENS E ADULTOS": "EDUCACAO JOVENS E ADULTOS",
    "EDUCACAO  JOVENS E ADULTOS": "EDUCACAO JOVENS E ADULTOS",
    "PROJOVEM": "EDUCACAO JOVENS E ADULTOS"
})

Alterando endereco_numero

In [ ]:
dataSet['endereco_numero'].unique()

array(['S/N', '653', '685', '180', '338', '369', '356', '1265', '255',
       '250', '300', 'SN', '53', '813', '198', '134', '1470', '37', '120',
       '1340', '290', '55', '82', '303', '80', '100', '453', '28', '84',
       '1595', '189', '131', '112', '111', '310', '450', '375', '1441',
       '5449', '48', '284', '10', '415', '633', '395', '19', '244', '479',
       '68', '1555', '215', '500', '25', '287', '83', '165', '568', '105',
       '49', '30', '7696', '127', '117', '35', '115', '175', '240', '427',
       '600', '320', '1138', '591', '91', '110', '925', '360', '222',
       '69', '211', '227', '655', '36', '85', '301', '304', '12', '13',
       '1406', '135', '437', '686', '440', '1864', '419', '498', '09',
       '273', '283', '1107', '51', '3895', '107', '350', '52', '125',
       '1316', '468', '700', '204', '42', '54', '508', '269', '176',
       '147', '157', '60', '1307', '318', '677', '182', '1030', '07',
       '900', '2173', '669', '109', '720', '56', '169', '24', '417',
       '1045', '511', '236', '141', '1040', '172', '21', '145', '27',
       '200', '216', '118', '43', '279', '594', '461', '377', '950',
       '545', '7636', '1848', '386', '168', '170', '399', '41', '541',
       '31', '660', '5785', '368', '225', '4900', '104', '2191', '160',
       '122', '2526', '140', '33', '470', '5400', '70', '570', '16',
       '364', '164', '50', '1800', '20', '248', '390', '123', '86', '218',
       '126A', '14', '1530', '65', '116', '73', '1536', '1120'],
      dtype=object)

In [ ]:
dataSet.loc[dataSet['endereco_numero'] == "S/N", 'endereco_numero'] = "SN"

Alterando RPA (Região Político Administrativa)

In [ ]:
dataSet['rpa'].unique()

array(['6', '4', '2', '1', '5', '3'], dtype=object)

In [ ]:
dataSet['rpa'] = dataSet['rpa'].replace({
    "1": "CENTRO",
    "2": "NORTE",
    "3": "NOROESTE",
    "4": "OESTE",
    "5": "SUDOESTE",
    "6": "SUL"
})

In [ ]:
dataSet['situacao_nome'].unique()

array(['APROVADO', 'TR DUR ANO FORA REDE', 'DESISTENTE', 'REPROVADO',
       'REPROVADO POR FALTA', 'FALECIDO', 'REMANEJADO',
       'TR DUR ANO P/REDE', 'RECLASSIFICADO', 'RENV NÃO DEFINIDA',
       'NUNCA COMPARECEU', 'DESISTENTE RENOVADO', 'TRANSFERÊNCIA'],
      dtype=object)

In [ ]:
dataSet['situacao_nome'].value_counts()

situacao_nome
APROVADO                76533
REPROVADO                4641
REPROVADO POR FALTA      4418
TR DUR ANO FORA REDE     4131
DESISTENTE               2950
RENV NÃO DEFINIDA        2015
TR DUR ANO P/REDE        1420
REMANEJADO                371
TRANSFERÊNCIA              96
FALECIDO                   43
DESISTENTE RENOVADO        19
RECLASSIFICADO             14
NUNCA COMPARECEU            7
Name: count, dtype: int64

In [ ]:
dataSet['situacao_nome'] = dataSet['situacao_nome'].replace({
    "RETIDO": "REPROVADO",
    "RETIDO POR FALTA": "REPROVADO POR FALTA",
    "REPROV P/  FALTA": "REPROVADO POR FALTA",
    "TR DUR ANO S/INFO": "TRANSFERÊNCIA",
    "RETIDO POR IDADE": "REPROVADO",
    "RT FALTA TR P/REDE": "TR DUR ANO P/REDE",
    "RETIDO E TR P/ REDE": "TR DUR ANO P/REDE",
    "Transferência": "TRANSFERÊNCIA",
    "DESIST/DEIXOU FREQUE": "DESISTENTE",
    "DESIST REN C/ TRANSF": "TRANSFERÊNCIA",
    "RENV S/SIT FINAL DEF": "RENV NÃO DEFINIDA",
    "FREQÜENTE": "APROVADO"

})

In [ ]:
def faixa_etaria(idade):
    if idade <= 10:
        return 'Criança'
    elif 11 <= idade <= 17:
        return 'Adolescente'
    else:
        return 'Adulto'

dataSet['faixa_etaria'] = dataSet['idade'].apply(faixa_etaria)

In [ ]:
dataSet.head(
)

,ano,codigo_escola,escola,endereco_bairro,endereco_logradouro,endereco_numero,rpa,ano_ensino,modalidade_ensino_codigo,serie_codigo,modalidade_ensino,turma,turno,matricula,sexo,idade,situacao_codigo,situacao_nome,faixa_etaria
0,2018,146,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,SN,SUL,GRUPO V,0,5.0,EDUCACAO INFANTIL,A,MANHÃ,17696089,Feminino,6,AP,APROVADO,Criança
1,2018,146,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,SN,SUL,GRUPO V,0,5.0,EDUCACAO INFANTIL,A,MANHÃ,16767969,Masculino,6,AP,APROVADO,Criança
2,2018,146,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,SN,SUL,GRUPO V,0,5.0,EDUCACAO INFANTIL,A,MANHÃ,17638470,Feminino,6,AP,APROVADO,Criança
3,2018,146,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,SN,SUL,GRUPO V,0,5.0,EDUCACAO INFANTIL,A,MANHÃ,17073731,Masculino,6,AP,APROVADO,Criança
4,2018,146,ABILIO GOMES,BOA VIAGEM,BRUNO VELOZO,SN,SUL,GRUPO V,0,5.0,EDUCACAO INFANTIL,A,MANHÃ,17711606,Feminino,6,AP,APROVADO,Criança

# **SAVE**

In [ ]:
# files.download('/content/situacaofinal2018.csv')